"""empty message

Revision ID: 829be9b7bf8c
Revises: f4e8473190f2
Create Date: 2023-09-15 14:07:43.557408

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '829be9b7bf8c'
down_revision = 'f4e8473190f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    if environment == "production":
        op.execute(f"ALTER TABLE holdings SET SCHEMA {SCHEMA};")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
