"""empty message

Revision ID: 7115d9c1cf89
Revises: 55543c6e410f
Create Date: 2023-09-13 14:43:05.233443

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '7115d9c1cf89'
down_revision = '55543c6e410f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('symbol', sa.Integer(), nullable=False))

    if environment == "production":
        op.execute(f"ALTER TABLE holdings SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_column('symbol')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
